debug: False
analysis: False
###########
# Dataset #
###########

data_root: './data'
batch_size: 10
num_workers: 16
eval_batch_size: 256
eval_num_workers: 4
batch_iter: 1

num_tasks: 5
longtail: True

#########
# Model #
#########

x_c: 1
x_h: 28
x_w: 28
y_c: 10

device: 'cuda'

e: 'mlp_classifier'
h1_dim: 64
h2_dim: 64

model_name: 'slab_rsvr'
reservoir_name: 'random'
reservoir_size: 300
replay_multiple: 1 # replayed batch size relative to input size.

reservoir_sample_num: 10
reservoir_batch_size: 10

# emb_dim: 512
# enc_dim: 2048 # due to resnet output
# dropout: 0.0
#
# Adaptive Replay batch
# Alter replay batch size buffer based on unique number of classes.
adaptive_replay: False


cost_sensitive: False

#########
# Train #
#########

weight_decay: 0.00001
implicit_lr_decay: False

optimizer_d:
  type: SGD
  options:
    lr: 0.01
    momentum: 0.9

lr_scheduler_d:
  type: MultiStepLR
  options:
    milestones: [1]
    gamma: 1.0

clip_grad:
  type: value
  options:
    clip_value: 0.5

########
# Eval #
########

eval: True

###########
# Summary #
###########

summary_step: 10
eval_step: 100
ckpt_step: 1000000000
summarize_samples: false

